### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by conceptfarm** [conceptfarm/pythonCompressor#1]
- [ ] File name parsing needs work, name_a_.0000.ext doesn't work , should output name_a.avi 
- [x] exr are still loaded when jpeg are available, may not be a bug, needs testing
- [ ] name collision detection, warning
- [x] Disable controls when compressing 
- [x] Configuration, path to ffmpeg, path to output
